# Conda environment file for Pacific Yew Density Model
# ======================================================
# To create environment: conda env create -f yew_pytorch_env.yml
# To activate: conda activate yew_pytorch
# To update: conda env update -f yew_pytorch_env.yml --prune

name: yew_pytorch

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10

  # PyTorch with CUDA 11.8 (matches your system)
  - pytorch::pytorch>=2.0
  - pytorch::torchvision>=0.15
  - pytorch::torchaudio>=2.0
  - pytorch::pytorch-cuda=11.8

  # Core scientific computing
  - numpy=1.26.4
  - pandas=2.2.1
  - scipy=1.11.4
  - matplotlib=3.8.0
  - seaborn=0.13.2
  - scikit-learn=1.3.0
  - scikit-image=0.22.0
  - pillow=10.2.0

  # Jupyter
  - jupyter
  - jupyterlab>=4.0
  - ipykernel
  - ipywidgets
  - ipympl

  # Development tools
  - pip
  - tqdm
  - pyyaml

  # Install via pip (packages not available or better via pip)
  - pip:
    # Deep learning utilities
    - tensorboard
    - torchmetrics
    - torchinfo
    - albumentations
    - segmentation-models-pytorch
    
    # Geospatial and Earth Engine
    - earthengine-api
    - geopandas
    - rasterio
    - shapely
    - pyproj
    - folium
    
    # ML experiment tracking
    - wandb
    - mlflow
    
    # Utilities
    - joblib
    - python-box
